[users]
DirkHoffmann = "H0ffmann123"
SuePiper = "Piper123"
NicoleIrvine = "Irvine123"
BesaLane = "Lane123"

[MAPBOX_TOKEN]
MAPBOX_TOKEN = "pk.eyJ1IjoiZGlya2hvZmZtYW5uIiwiYSI6ImNtaWVrNnFxaTAzaXEzZnIxamduYngyM20ifQ.xf-AmrSPFjTzsVqc8Rvn8g"
